url: "http://127.0.0.1:4000"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from

kramdown:
  input: Kramdown
